// domain/repository.go — interface
type UserRepository interface {
    FindByID(ctx context.Context, id string) (*User, error)
    FindByEmail(ctx context.Context, email string) (*User, error)
    Save(ctx context.Context, user *User) error
    Delete(ctx context.Context, id string) error
}

// infrastructure/postgres_user_repo.go
type PostgresUserRepo struct {
    queries *sqlcgen.Queries  // generated by sqlc
}

func NewPostgresUserRepo(db *sql.DB) *PostgresUserRepo {
    return &PostgresUserRepo{queries: sqlcgen.New(db)}
}

func (r *PostgresUserRepo) FindByID(
    ctx context.Context, id string,
) (*User, error) {
    row, err := r.queries.GetUserByID(ctx, id)
    if err != nil {
        if errors.Is(err, sql.ErrNoRows) {
            return nil, nil
        }
        return nil, fmt.Errorf("find user by id: %w", err)
    }
    return toDomainUser(row), nil
}

func (r *PostgresUserRepo) Save(
    ctx context.Context, user *User,
) error {
    return r.queries.UpsertUser(ctx, sqlcgen.UpsertUserParams{
        ID: user.ID, Email: user.Email, Name: user.Name,
    })
}
